### ISSUE TITLE
-h flag throws error

### ISSUE THREAD

**Issue by ethanagb** [ethanagbaker/pblibsim#1]
prints usage lines, but then gives following traceback:

``` python
Traceback (most recent call last):
  File "../v1/generate_chrdist.py", line 58, in <module>
    GenerateChrDist(sys.argv[1:])
  File "../v1/generate_chrdist.py", line 20, in GenerateChrDist
    with open(infileName,'r') as infile:
IOError: [Errno 2] No such file or directory: ''
```

Seems to be still looking for -i file, but shouldn't be

**Comment by ethanagb** [comment]
Added `sys.exit(2)`, fixed arg parsing
